# Generated by Django 4.1.1 on 2022-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
